### ISSUE TITLE
Unobserved latent variables

### ISSUE THREAD

**Issue by chenjie** [JohnGiorgi/CSC412-2506-course-notes#5]
https://johngiorgi.github.io/CSC412-2506-course-notes/lectures/week_3/#latent-variables

I don't understand how you derive the following equation. Could you please clarify a bit?

> E.g., given \(y\), \(x\) fit the model \(p(z, y|x) = p(z|y)p(y|x, w)p(w)\). In other words if it is a leaf node.

**Comment by JohnGiorgi** [comment]
Sorry! 

I don't really understand it myself. It comes from the lecture 3 slides if that helps.
